#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jun 15 15:16:26 IST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_time_synth -key {Post-Synthesis:sim_1:Timing:tb} -tclbatch tb.tcl -view /home/varun/coding/fpga/xylinx/zynq/ws2812/tb_behav.wcfg -log simulate.log"
xsim tb_time_synth -key {Post-Synthesis:sim_1:Timing:tb} -tclbatch tb.tcl -view /home/varun/coding/fpga/xylinx/zynq/ws2812/tb_behav.wcfg -log simulate.log

